
# Let's Configure Delightful
[Knives]
	amethyst_knife = true
	black_opal_knife = false
	bone_knife = true
	brass_knife = true
	bronze_knife = true
	constantan_knife = true
	copper_knife = true
	deorum_knife = false
	draco_arcanus_knife = false
	electrum_knife = true
	emerald_knife = true
	enderite_knife = false
	fiery_knife = true
	invar_knife = true
	ironwood_knife = false
	knightmetal_knife = false
	lapis_lazuli_knife = true
	large_amethyst_knife = false
	lead_knife = true
	living_knife = false
	netherite_opal_knife = false
	nickel_knife = true
	obsidian_infused_enderite_knife = false
	osmium_knife = true
	refined_glowstone_knife = true
	refined_obsidian_knife = true
	reinforced_deorum_knife = true
	silver_knife = true
	steel_knife = true
	steeleaf_knife = false
	tin_knife = true

[Cabinets]
	basalt_cabinet = true
	quartz_cabinet = true

["Foods and Other Items"]
	acorn = true
	acorn_sack = true
	animal_fat = false
	animal_oil_bottle = false
	azalea_tea = true
	berry_matcha_latte = true
	cactus_flesh = true
	cactus_steak = true
	cheeseburger = true
	chopped_clover = false
	chunk_nugget = false
	chunkwich = false
	cooked_goat = true
	cooked_marshmallow_stick = true
	cooked_venison_chops = true
	crab_rangoon = false
	deluxe_cheeseburger = true
	ender_nectar = true
	field_salad = true
	glow_jelly_bottle = true
	green_tea_leaf = false
	honey_glazed_walnut = true
	jelly_bottle = true
	lavender_tea = true
	marshmallow_stick = true
	matcha = true
	matcha_latte = true
	mini_melon = false
	nut_butter_and_jelly_sandwich = true
	nut_butter_bottle = true
	prickly_pear_juice = true
	raw_goat = true
	rock_candy = true
	salmonberries = false
	salmonberry_pips = false
	salmonberry_sack = false
	smore = true
	venison_chops = true
	#Allow cooking milk from nuts
	nut_milk = false
	#Allow cooking honey from honey and clovers
	clover_honey = false

[Generation]
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	chance_wild_salmonberries = 30
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	chance_mini_melon = 30

