onEvent('server.datapack.high_priority', event => {
  [
    'apprenticebloodorb',
    'archmagebloodorb',
    'daggerofsacrifice',
    'demonicslate',
    'etherealslate',
    'weakbloodorb',
    'imbuedslate',
    'magicianbloodorb',
    'masterbloodorb',
    'reinforcedslate',
    'alchemy_flask',
    'bleeding_edge_music',
    'earth_tool',
    'enhanced_teleposer_focus',
    'fire_tool',
    'slate',
    'telepoposer_focus',
  ].forEach(id => event.addJson(`bloodmagic:recipes/altar/${id}.json`, {}));
});

onEvent('recipes', event => {
  new recipes(event)
    .setType('create:crushing')
    .setFunction(config =>
      event.custom({
        type: 'bloodmagic:altar',
        input: {
          item: config.input,
        },
        output: {
          item: config.output,
        },
        upgradeLevel: config.level || 0,
        altarSyphon: config.syphon,
        consumptionRate: config.rate,
        drainRate: config.rate,
      })
    )
    .modifyOutputs([
      {
        global: true,
        input: 'create:sturdy_sheet',
        level: 2,
        syphon: 40000,
        rate: 40,
        output: 'bloodmagic:activationcrystalweak',
      },
      {
        global: true,
        input: 'bloodmagic:fortune_anointment',
        level: 2,
        syphon: 2000,
        rate: 2,
        output: 'bloodmagic:earthscribetool',
      },
      {
        global: true,
        input: 'bloodmagic:bow_velocity_anointment',
        level: 2,
        syphon: 2000,
        rate: 2,
        output: 'bloodmagic:airscribetool',
      },
      {
        global: true,
        input: 'bloodmagic:holy_water_anointment',
        level: 2,
        syphon: 2000,
        rate: 2,
        output: 'bloodmagic:waterscribetool',
      },
      {
        global: true,
        input: 'bloodmagic:smelting_anointment',
        level: 2,
        syphon: 2000,
        rate: 2,
        output: 'bloodmagic:firescribetool',
      },
      {
        global: true,
        input: 'undergarden:mogmoss',
        syphon: 2000,
        rate: 2,
        output: 'bloodmagic:arcaneashes',
      },
      {
        global: true,
        input: 'bloodmagic:ingot_hellforged',
        syphon: 500000,
        level: 4,
        rate: 500,
        output: 'bloodsmeltery:bloodbrass_ingot',
      },
      {
        global: true,
        input: 'blue_skies:venom_sac',
        syphon: 5000,
        level: 1,
        rate: 5,
        output: 'bloodmagic:daggerofsacrifice',
      },
      {
        global: true,
        input: 'bloodmagic:rawdemoniteblock',
        syphon: 1000000,
        rate: 1000,
        level: 4,
        output: 'bloodmagic:bleedingedge',
      },
      {
        global: true,
        output: 'bloodmagic:weakbloodorb',
        input: 'undergarden:utherium_crystal',
        syphon: 5000,
        rate: 5,
      },
      {
        global: true,
        output: 'bloodmagic:apprenticebloodorb',
        input: 'tconstruct:slimesteel_block',
        syphon: 50000,
        level: 1,
        rate: 50,
      },
      {
        global: true,
        output: 'bloodmagic:magicianbloodorb',
        input: 'twilightforest:fiery_block',
        syphon: 100000,
        level: 2,
        rate: 20,
      },
      {
        global: true,
        output: 'bloodmagic:masterbloodorb',
        input: 'bloodmagic:weakbloodshard',
        syphon: 250000,
        level: 3,
        rate: 500,
      },
      {
        global: true,
        output: 'bloodmagic:archmagebloodorb',
        input: 'bloodmagic:dungeon_metal',
        syphon: 10000000,
        level: 4,
        rate: 1500,
      },
      {
        global: true,
        input: 'rankine:snowflake_obsidian',
        output: 'rankine:blood_obsidian',
        syphon: 2000,
        level: 1,
        rate: 2,
      },
      {
        global: true,
        input: 'rankine:slate',
        output: 'bloodmagic:blankslate',
        syphon: 1000,
        rate: 1,
      },
      {
        global: true,
        input: 'bloodmagic:blankslate',
        output: 'bloodmagic:reinforcedslate',
        level: 1,
        syphon: 5000,
        rate: 5,
      },
      {
        global: true,
        input: 'bloodmagic:reinforcedslate',
        output: 'bloodmagic:infusedslate',
        level: 2,
        syphon: 10000,
        rate: 10,
      },
      {
        global: true,
        input: 'butchercraft:pork_scraps',
        output: 'butchercraft:lamb_scraps',
        level: 3,
        syphon: 50000,
        rate: 200,
      },
      {
        global: true,
        input: 'butchercraft:lamb_scraps',
        output: 'butchercraft:beef_scraps',
        level: 3,
        syphon: 100000,
        rate: 200,
      },
      {
        global: true,
        input: 'minecraft:dragon_breath',
        output: 'minecraft:chorus_fruit',
        level: 3,
        syphon: 150000,
        rate: 300,
      },
      {
        global: true,
        input: 'botania:diluted_pool',
        output: 'botania:mana_pool',
        level: 3,
        syphon: 20000,
        rate: 200,
      },
      {
        global: true,
        input: 'create:shadow_steel',
        output: 'bloodmagic:demonslate',
        level: 3,
        syphon: 50000,
        rate: 50,
      },
      {
        global: true,
        input: 'butchercraft:ground_beef',
        output: 'bloodmagic:demonslate',
        level: 3,
        syphon: 12500,
        rate: 50,
      },
      {
        global: true,
        input: 'butchercraft:ground_pork',
        output: 'bloodmagic:demonslate',
        level: 3,
        syphon: 25000,
        rate: 50,
      },
      {
        global: true,
        input: 'butchercraft:ground_lamb',
        output: 'bloodmagic:demonslate',
        level: 3,
        syphon: 12500,
        rate: 50,
      },
      {
        global: true,
        input: 'bloodmagic:demonslate',
        output: 'bloodmagic:etherealslate',
        level: 4,
        syphon: 1000000,
        rate: 1000,
      },
      {
        global: true,
        input: 'charcoal_pit:nether_shard',
        output: 'chunkloaders:single_chunk_loader',
        level: 2,
        syphon: 15000,
        rate: 5,
      },
      {
        global: true,
        input: 'chunkloaders:single_chunk_loader',
        output: 'chunkloaders:basic_chunk_loader',
        level: 3,
        syphon: 30000,
        rate: 30,
      },
      {
        global: true,
        input: 'chunkloaders:basic_chunk_loader',
        output: 'chunkloaders:advanced_chunk_loader',
        level: 3,
        syphon: 100000,
        rate: 100,
      },
      {
        global: true,
        input: 'chunkloaders:advanced_chunk_loader',
        output: 'chunkloaders:ultimate_chunk_loader',
        level: 4,
        syphon: 200000,
        rate: 200,
      },
    ])
    .add([
      {
        input: 'bloodmagic:strong_tau',
        output: 'chunkloaders:single_chunk_loader',
        level: 3,
        syphon: 10000,
        rate: 10,
      },
      {
        input: 'blue_skies:spider_webbing',
        output: 'bloodmagic:soulsnare',
        level: 0,
        syphon: 500,
        rate: 5,
      },
      {
        input: 'occultism:book_of_binding_djinni',
        output: 'occultism:book_of_binding_afrit',
        level: 1,
        syphon: 20000,
        rate: 20,
      },
    ]);
});
