onEvent('recipes', event => {
  new recipes(event)
    .setType('minecraft:campfire_cooking')
    .setFunction(config => event.campfireCooking(config.output, config.input))
    .removeOutputs([
      'delightful:cooked_venison_chops',
      'delightful:cooked_goat',
      'butchercraft:cooked_beef_scraps',
      'butchercraft:cooked_ground_beef',
      'butchercraft:cooked_cubed_beef',
      'butchercraft:cooked_beef_ribs',
      'butchercraft:cooked_beef_rib',
      'butchercraft:cooked_beef_roast',
      'butchercraft:cooked_beef_stewmeat',
      'butchercraft:cooked_oxtail',
      'butchercraft:cooked_tongue',
      'butchercraft:cooked_pork_scraps',
      'butchercraft:cooked_ground_pork',
      'butchercraft:cooked_cubed_pork',
      'butchercraft:cooked_pork_ribs',
      'butchercraft:cooked_pork_rib',
      'butchercraft:cooked_pork_roast',
      'butchercraft:cooked_pork_stewmeat',
      'butchercraft:cooked_bacon',
      'butchercraft:cooked_lamb_scraps',
      'butchercraft:cooked_ground_lamb',
      'butchercraft:cooked_cubed_lamb',
      'butchercraft:cooked_lamb_ribs',
      'butchercraft:cooked_lamb_rib',
      'butchercraft:cooked_lamb_roast',
      'butchercraft:cooked_lamb_stewmeat',
      'butchercraft:cooked_sausage',
      'butchercraft:cooked_tripe',
      'butchercraft:cooked_stomache',
      'butchercraft:cooked_lung',
      'butchercraft:cooked_liver',
      'butchercraft:cooked_kidney',
      'butchercraft:cooked_heart',
      'butchercraft:cooked_brain',
      'butchercraft:cooked_beef_block_item',
      'butchercraft:cooked_pork_block_item',
      'butchercraft:cooked_lamb_block_item',
      Item.of('thirst:terracotta_water_bowl').ignoreNBT(),
      'thirst:terracotta_bowl',
      Item.of('minecraft:potion').ignoreNBT(),
      Item.of('minecraft:water_bucket').ignoreNBT(),
      'rankine:bone_ash',
      'minecraft:bread',
      'charcoal_pit:popcorn',
      'rankine:refractory_brick',
      'minecraft:torch',
      'rankine:toast',
      'rankine:pancake',
      'blue_skies:cooked_horizofin_tunid',
      'twilightforest:cooked_meef',
      'farmersdelight:cooked_mutton_chops',
      'minecraft:cooked_beef',
      'farmersdelight:cooked_chicken_cuts',
      'rankine:cooked_tofu',
      'minecraft:cooked_rabbit',
      'farmersdelight:beef_patty',
      'farmersdelight:fried_egg',
      'minecraft:cooked_porkchop',
      'blue_skies:cooked_monitor_tail',
      'minecraft:cooked_chicken',
      'minecraft:cooked_mutton',
      'twilightforest:cooked_venison',
      'farmersdelight:cooked_bacon',
      'blue_skies:cooked_charscale_moki',
      'minecraft:charcoal',
      'minecraft:bone',
    ])
    .add([
      {
        input: 'realistictorches:unlit_torch',
        output: 'realistictorches:lit_torch',
      },
      {
        input: 'farmersrespite:green_tea_leaves',
        output: 'farmersrespite:yellow_tea_leaves',
      },
      {
        input: 'farmersrespite:yellow_tea_leaves',
        output: 'farmersrespite:black_tea_leaves',
      },
      {
        input: 'delightful:cactus_flesh',
        output: 'delightful:cactus_steak',
      },
      {
        input: 'charcoal_pit:unfired_brick',
        output: 'minecraft:brick',
      },
      {
        input: Item.of('thirst:terracotta_water_bowl', '{Purity: 0}'),
        output: Item.of('thirst:terracotta_water_bowl', '{Purity: 1}'),
      },
      {
        input: Item.of('thirst:terracotta_water_bowl', '{Purity: 1}'),
        output: Item.of('thirst:terracotta_water_bowl', '{Purity: 2}'),
      },
    ]);
});
