onEvent('recipes', event => {
  new recipes(event)
    .setType('minecraft:smelting')
    .setFunction(config => event.smelting(config.output, config.input))
    .removeInputs(['delightful:bone_knife'])
    .removeOutputs([
      'delightful:cactus_steak',
      'delightful:cooked_venison_chops',
      'delightful:cooked_goat',
      'butchercraft:cooked_beef_scraps',
      'butchercraft:cooked_ground_beef',
      'butchercraft:cooked_cubed_beef',
      'butchercraft:cooked_beef_ribs',
      'butchercraft:cooked_beef_rib',
      'butchercraft:cooked_beef_roast',
      'butchercraft:cooked_beef_stewmeat',
      'butchercraft:cooked_oxtail',
      'butchercraft:cooked_tongue',
      'butchercraft:cooked_pork_scraps',
      'butchercraft:cooked_ground_pork',
      'butchercraft:cooked_cubed_pork',
      'butchercraft:cooked_pork_ribs',
      'butchercraft:cooked_pork_rib',
      'butchercraft:cooked_pork_roast',
      'butchercraft:cooked_pork_stewmeat',
      'butchercraft:cooked_bacon',
      'butchercraft:cooked_lamb_scraps',
      'butchercraft:cooked_ground_lamb',
      'butchercraft:cooked_cubed_lamb',
      'butchercraft:cooked_lamb_ribs',
      'butchercraft:cooked_lamb_rib',
      'butchercraft:cooked_lamb_roast',
      'butchercraft:cooked_lamb_stewmeat',
      'butchercraft:cooked_sausage',
      'butchercraft:cooked_tripe',
      'butchercraft:cooked_stomache',
      'butchercraft:cooked_lung',
      'butchercraft:cooked_liver',
      'butchercraft:cooked_kidney',
      'butchercraft:cooked_heart',
      'butchercraft:cooked_brain',
      'butchercraft:cooked_beef_block_item',
      'butchercraft:cooked_pork_block_item',
      'butchercraft:cooked_lamb_block_item',
      '#forge:ingots',
      '@coinsje',
      '#forge:gems',
      '#forge:nuggets',
      '#forge:glass',
      'minecraft:bread',
      'rankine:refractory_brick',
      'pneumaticcraft:sourdough_bread',
      'occultism:iesnium_ingot',
      '#forge:glass_panes',
      'rankine:refractory_brick',
      'minecraft:torch',
      'rankine:toast',
      'rankine:pancake',
      'blue_skies:cooked_horizofin_tunid',
      'twilightforest:cooked_meef',
      'farmersdelight:cooked_mutton_chops',
      'minecraft:cooked_beef',
      'farmersdelight:cooked_chicken_cuts',
      'rankine:cooked_tofu',
      'minecraft:cooked_rabbit',
      'farmersdelight:beef_patty',
      'farmersdelight:fried_egg',
      'minecraft:cooked_porkchop',
      'blue_skies:cooked_monitor_tail',
      'minecraft:cooked_chicken',
      'minecraft:cooked_mutton',
      'twilightforest:cooked_venison',
      'farmersdelight:cooked_bacon',
      'blue_skies:cooked_charscale_moki',
      'blue_skies:cooked_grittle_flatfish',
      'minecraft:blue_glazed_terracotta',
      'industrialforegoing:plastic',
      'charcoal_pit:cooked_calamari',
      'minecraft:popped_chorus_fruit',
      'minecraft:lime_dye',
      'minecraft:lime_glazed_terracotta',
      'hem:rose_copper_ingot',
      'minecraft:pink_glazed_terracotta',
      'minecraft:cooked_salmon',
      'minecraft:slime_ball',
      'minecraft:red_glazed_terracotta',
      'minecraft:white_glazed_terracotta',
      'minecraft:paper',
      'blue_skies:cooked_municipal_monkfish',
      'hem:bronze_ingot',
      'minecraft:cyan_glazed_terracotta',
      'minecraft:green_dye',
      'minecraft:baked_potato',
      'undergarden:cooked_gwibling',
      'undergarden:gloomper_leg',
      'undergarden:dweller_steak',
      'minecraft:magenta_glazed_terracotta',
      'minecraft:black_glazed_terracotta',
      'farmersdelight:cooked_cod_slice',
      'immersiveengineering:ingot_hop_graphite',
      'minecraft:green_glazed_terracotta',
      'minecraft:orange_glazed_terracotta',
      'minecraft:gray_glazed_terracotta',
      'minecraft:cooked_cod',
      'minecraft:redstone',
      'rankine:dried_bamboo',
      'charcoal_pit:popcorn',
      'blue_skies:cooked_venison',
      'minecraft:yellow_glazed_terracotta',
      'pneumaticcraft:plastic',
      'farmersdelight:cooked_salmon_slice',
      'minecraft:brown_glazed_terracotta',
      'undergarden:roasted_underbeans',
      'blue_skies:moonstone',
      'minecraft:furnace',
      'blue_skies:cooked_carabeef',
      'minecraft:light_gray_glazed_terracotta',
      'minecraft:coal',
      'rankine:ash',
      'bloodmagic:saltpeter',
      'minecraft:light_blue_glazed_terracotta',
      'minecraft:purple_glazed_terracotta',
      'minecraft:dried_kelp',
    ])
    .add([
      {
        input: 'malum:raw_soulstone',
        output: 'malum:processed_soulstone',
      },
      {
        input: 'malum:crushed_soulstone',
        output: 'malum:processed_soulstone',
      },
      {
        input: 'ecofriendly:iron_can_ym',
        output: 'ecofriendly:smelted_iron_can_ym',
      },
      {
        input: 'charcoal_pit:unfired_brick',
        output: 'minecraft:brick',
      },
      {
        input: 'rankine:limestone',
        output: 'rankine:quicklime',
      },
      {
        input: 'rankine:fire_clay_ball',
        output: 'rankine:refractory_brick',
      },
    ]);
});
