[Mods]
ding = "client"
rubidium = "client"
AdvancementPlaques = "client"
appleskin-forge = "client"
BetterAdvancements = "client"
BetterF3 = "client"
BetterModsButton = "client"
catalogue = "client"
ConfigMenusForge = "client"
Controlling = "client"
CTM = "client"
embeddium = "client"
Jade = "client"
jeiintegration = "client"
kubejs-ui = "client"
MouseTweaks = "client"
Overloaded = "client"
player-animation-lib = "client"
ponderjs = "client"
probejs = "client"
shutupexperimentalsettings = "client"
StylishEffects = "client"
ToastControl = "client"
Xaeros_Minimap = "client"
XaerosWorldMap = "client"